### ISSUE TITLE
[BUG] Doesn't work anymore with Firefox 123.0 on Linux

### ISSUE THREAD

**Issue by muellerjoel** [ninoseki/mitaka#796]
### **Steps to reproduce**

- Select a IP as Text
- Right-Click
- No Menu entry with Mitaka

### **Expected behavior**

- Mitaka menupoint is displayed

### **Actual behavior**

A clear and concise description of what actually happened.

### **Screenshots**
![Screenshot 2024-02-27 at 22-13-56 ↓ 1 84 kB_s ↑ 12 7 MB_s - Flood](https://github.com/ninoseki/mitaka/assets/76882403/7a7b7c5d-4c2f-495d-95b9-dddc8f28049f)

![20240227_22h15m08s_grim](https://github.com/ninoseki/mitaka/assets/76882403/69d42484-0225-4e6b-aea4-9b666cb3c8c2)

### **System Information:**

- OS: Arch Linux 6.5.6
- Browser: Firefox 123
- Mitaka version: 2.0.0

**Comment by ninoseki** [comment]
I can reproduce the issue by myself and I fixed the issue in the latest version. 
https://addons.mozilla.org/en-US/firefox/addon/mitaka/
Please try it.

**Comment by muellerjoel** [comment]
![20240228_12h26m46s_grim](https://github.com/ninoseki/mitaka/assets/76882403/9cae87b1-c112-4427-b6bd-81fa1741102b)

It's still not working with right-click

**Comment by ninoseki** [comment]
I can take a look at it if you could provide errors logs. Otherwise I can do nothing.

**Comment by muellerjoel** [comment]
![20240228_16h47m20s_grim](https://github.com/ninoseki/mitaka/assets/76882403/e77ca49d-abdf-449d-8635-e75045001efc)
![20240228_16h46m48s_grim](https://github.com/ninoseki/mitaka/assets/76882403/7c7bde3e-7125-4439-a6ae-380ed14dcd5f)

Works now a reboot does good but a error in the debugging windows
